### ISSUE TITLE
Extraction depuis base PostGIS avec GDAL recompilé

### ISSUE THREAD

**Issue by bchartier** [neogeo-technologies/idgo-extractor#3]
Je rencontre des soucis avec l'extracteur d'IDGO avec PostGIS.
2 cas de figure distincts posent problème (cf. description plus bas) et uniquement avec le déploiement sur le serveur de recette.
Pour ce serveur nous avons réalisé une compilation spécifique de GDAL afin de supporter ECW.

A noter que  :
- ces erreurs ne se produisent pas quand on fait la même extraction sur un jeu de données identique mais stocké sous forme de shapefile.
- ces erreurs ne se produisent pas avec la version dockerisée avec le GDAL tel que défini dans le dockerfile du projet guthub.

Je soupçonne un souci avec la compilation de GDAL mais sans en être certain.
@rouault : est-ce que tu aurais une idée sur la manière dont je pourrais procéder pour identifier la cause de ces problèmes ?

**Cas de figure 1 :**
Demande d'extraction sans footprint :
```
{
    "user_id": "my_id",
    "user_id": "my_id",
    "user_email_address": "truc@machin.fr",
    "user_name": "Truc",
    "user_first_name": "Machin",
    "source": "PG:host=postgis-master dbname=extractor_default schemas=recette user=idgo_extractor",
    "dst_format": {
        "gdal_driver": "ESRI Shapefile"
    },
    "dst_srs": "EPSG:2154",
    "layer": "lycees_2015"
}
```

L'extraction semble bien se passer mais le jeu de données extrait ne contient aucun enregistrement. Par contre, les noms des champs sont bons. Même résultat quel que soit le jeu de données en base et quel que soit le format de données demandé en sortie.

**Cas de figure 2 :**
Demande d'extraction avec un footprint :
```
{
    "user_id": "my_id",
    "user_email_address": "truc@machin.fr",
    "user_name": "Truc",
    "user_first_name": "Machin",
    "source": "PG:host=postgis-master dbname=extractor_default schemas=recette user=idgo_extractor",
    "dst_format": {
        "gdal_driver": "ESRI Shapefile"
    },
    "dst_srs": "EPSG:2154",
    "footprint": "Polygon ((828762.75076655030716211 6349612.76035964675247669, 828054.16994170041289181 6224548.24477365612983704, 919461.09634732489939779 6224193.95436122734099627, 912020.99768640205729753 6349258.46994722355157137, 828762.75076655030716211 6349612.76035964675247669))",
    "footprint_srs": "EPSG:2154",
    "layer": "lycees_2015"
}
```

Une exception est levée pendant le traitement :

```
Dec 13 11:20:50 idgo-extractor celery[28451]: Traceback (most recent call last):
Dec 13 11:20:50 idgo-extractor celery[28451]:   File "/usr/local/lib/python3.5/dist-packages/billiard/process.py", line 327, in _bootstrap
Dec 13 11:20:50 idgo-extractor celery[28451]:     self.run()
Dec 13 11:20:50 idgo-extractor celery[28451]:   File "/usr/local/lib/python3.5/dist-packages/billiard/process.py", line 114, in run
Dec 13 11:20:50 idgo-extractor celery[28451]:     self._target(*self._args, **self._kwargs)
Dec 13 11:20:50 idgo-extractor celery[28451]:   File "/apps/idgo-extractor/celery/extractions.py", line 197, in decorated_function
Dec 13 11:20:50 idgo-extractor celery[28451]:     res = f(process_func_args, callback, callback_data)
Dec 13 11:20:50 idgo-extractor celery[28451]:   File "/apps/idgo-extractor/celery/extractions.py", line 598, in process_vector
Dec 13 11:20:50 idgo-extractor celery[28451]:     footprint_geom.TransformTo(layer.GetSpatialRef())
Dec 13 11:20:50 idgo-extractor celery[28451]:   File "/usr/lib/python3/dist-packages/osgeo/ogr.py", line 6948, in TransformTo
Dec 13 11:20:50 idgo-extractor celery[28451]:     return _ogr.Geometry_TransformTo(self, *args)
Dec 13 11:20:50 idgo-extractor celery[28451]: ValueError: Received a NULL pointer.
Dec 13 11:20:50 idgo-extractor celery[28451]: [2017-12-13 11:20:50,024: WARNING/Process-1:14] Process Process-1:14:
Dec 13 11:20:50 idgo-extractor celery[28451]: [2017-12-13 11:20:50,024: WARNING/Process-1:14] Traceback (most recent call last):
Dec 13 11:20:50 idgo-extractor celery[28451]: [2017-12-13 11:20:50,025: WARNING/Process-1:14] File "/usr/local/lib/python3.5/dist-packages/billiard/process.p
y", line 327, in _bootstrap
Dec 13 11:20:50 idgo-extractor celery[28451]:     self.run()
Dec 13 11:20:50 idgo-extractor celery[28451]: [2017-12-13 11:20:50,025: WARNING/Process-1:14] File "/usr/local/lib/python3.5/dist-packages/billiard/process.p
y", line 114, in run
Dec 13 11:20:50 idgo-extractor celery[28451]:     self._target(*self._args, **self._kwargs)
Dec 13 11:20:50 idgo-extractor celery[28451]: [2017-12-13 11:20:50,026: WARNING/Process-1:14] File "/apps/idgo-extractor/celery/extractions.py", line 197, in
 decorated_function
Dec 13 11:20:50 idgo-extractor celery[28451]:     res = f(process_func_args, callback, callback_data)
Dec 13 11:20:50 idgo-extractor celery[28451]: [2017-12-13 11:20:50,026: WARNING/Process-1:14] File "/apps/idgo-extractor/celery/extractions.py", line 598, in
 process_vector
Dec 13 11:20:50 idgo-extractor celery[28451]:     footprint_geom.TransformTo(layer.GetSpatialRef())
Dec 13 11:20:50 idgo-extractor celery[28451]: [2017-12-13 11:20:50,027: WARNING/Process-1:14] File "/usr/lib/python3/dist-packages/osgeo/ogr.py", line 6948,
in TransformTo
Dec 13 11:20:50 idgo-extractor celery[28451]:     return _ogr.Geometry_TransformTo(self, *args)
Dec 13 11:20:50 idgo-extractor celery[28451]: [2017-12-13 11:20:50,027: WARNING/Process-1:14] ValueError: Received a NULL pointer.
Dec 13 11:20:50 idgo-extractor celery[28451]: [2017-12-13 11:20:50,118: INFO/ForkPoolWorker-1] Removed dir /nas/tmp/IDGO_EXTRACT_5bd68e30-dbcf-4515-ad5c-6a2f
418256aa-f5b2kvjw
Dec 13 11:20:50 idgo-extractor celery[28451]: [2017-12-13 11:20:50,119: ERROR/ForkPoolWorker-1] failure occured: {'request': {'footprint': 'POLYGON ((828762.
75076655 6349612.76035965,828054.1699417 6224548.24477366,919461.096347325 6224193.95436123,912020.997686402 6349258.46994722,828762.75076655 6349612.7603596
5))', 'user_address': '18 rue de Bayard - 31000 Toulouse', 'dst_format': {'gdal_driver': 'ESRI Shapefile'}, 'source': 'PG:host=postgis-master dbname=extracto
r_default schemas=recette user=idgo_extractor', 'footprint_srs': 'EPSG:2154', 'layer': 'lycees_2015', 'dst_srs': 'EPSG:2154', 'user_id': 'my_id', 'user_name'
: 'Chartier', 'user_email_address': 'bchartier@neogeo.fr', 'user_company': 'Neogeo Technologies', 'user_first_name': 'Benjamin'}, 'exception': 'Received a NU
LL pointer.', 'hostname': 'celery@idgo-extractor', 'pid': 28457}
Dec 13 11:20:50 idgo-extractor celery[28451]: [2017-12-13 11:20:50,120: INFO/ForkPoolWorker-1] Task extraction.do[5bd68e30-dbcf-4515-ad5c-6a2f418256aa] raise
d expected: OperationalError('Received a NULL pointer.',)
```

**Comment by bchartier** [comment]
Pour le cas de figure 2 avec l'exception, cela viendrait de la ligne suivante :      
`footprint_geom.TransformTo(layer.GetSpatialRef())`
cf. https://github.com/neogeo-technologies/idgo-extractor/blob/master/celery/extractions.py#L564

Pour tant le code EPSG est bien spécifié dans la définition de la table :
```
CREATE TABLE recette.lycees_2015
(
    id integer NOT NULL DEFAULT nextval('recette.lycees_2015_id_seq'::regclass),
    geom geometry(MultiPointZ,2154),
[...]
```

Est-ce que cela pourrait venir d'un souci avec proj4 ?

**Comment by rouault** [comment]
Quelle version d'idgo-extractor est exactement déployée ? Car dans l'exception il s'agit de la ligne 598, alors que dans le master c'est effectivement la ligne 564.

Pour le cas de figure 2, mon hypothèse est que le GDAL recompilé ne trouve pas son répertoire de resources contenant la base EPSG sous forme de fichiers CSV. Normalement il s'agit du répertoire ${prefix}/share/gdal si on a configuré GDAL avec ./configure --prefix=${prefix}. Il est également possible de le surcharger en faisant pointer la variable d'environnement GDAL_DATA vers ce répertoire. Tu peux essayer de rajouter une trace de déboggage print(footprint_srs) juste après https://github.com/neogeo-technologies/idgo-extractor/blob/master/celery/extractions.py#L561 ```footprint_srs.SetFromUserInput(footprint_srs_wkt)```. Normalement ça devrait afficher le WKT correspondant à EPSG:2154. Là je soupçonne que ça affiche du vide.

Ce qui est bizarre c'est que le SRS de footprint_srs est vérifié par le frontend : https://github.com/neogeo-technologies/idgo-extractor/blob/master/frontend/app.py#L248 . Ca voudrait donc dire que la version GDAL du frontend est différente de celle du backend ?

Pour le cas de figure 1, c'est plus curieux. S'il y a effectivement un souci de GDAL_DATA, l'appel gdal.VectorTranslate() devrait retourner une erreur (mais pas sous la forme d'exception) du genre  """ERROR 4: Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files. Failed to process SRS definition: EPSG:2154""". Il n'y a vraiment rien dans les logs ? Et le fait que ça soit spécifique à une source PostGIS m'intrigue. Que se passe-t-il si tu te loggues sur ce serveur et lance ```ogr2ogr -t_srs EPSG:2154 out.shp "PG:host=postgis-master dbname=extractor_default schemas=recette user=idgo_extractor" lycees_2015```

**Comment by bchartier** [comment]
> Quelle version d'idgo-extractor est exactement déployée ? Car dans l'exception il s'agit de la ligne 598, alors que dans le master c'est effectivement la ligne 564.

Il y a effectivement un décalage entre la version master de github et ce qui est déployé sur le serveur. C'est bien la ligne `footprint_geom.TransformTo(layer.GetSpatialRef())` (correspond à la ligne 564 du master qui pose souci pour l'exception du cas de figure 2).

> Ce qui est bizarre c'est que le SRS de footprint_srs est vérifié par le frontend : https://github.com/neogeo-technologies/idgo-extractor/blob/master/frontend/app.py#L248 . Ca voudrait donc dire que la version GDAL du frontend est différente de celle du backend ?

Je vais regarder cela.

> Pour le cas de figure 1, c'est plus curieux. S'il y a effectivement un souci de GDAL_DATA, l'appel gdal.VectorTranslate() devrait retourner une erreur (mais pas sous la forme d'exception) du genre """ERROR 4: Unable to open EPSG support file gcs.csv. Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files. Failed to process SRS definition: EPSG:2154""". Il n'y a vraiment rien dans les logs ? Et le fait que ça soit spécifique à une source PostGIS m'intrigue.

Dans les logs on a effectivement une erreur mais pas celle que tu évoques :
`Dec 13 16:28:43 idgo-extractor celery[28451]: ERROR 1: ERREUR:  droit refusé pour la relation lycees_2015`
J'avais vu cette erreur mais j'avais oublié de regarder les droits dans PostgreSQL. ça explique le dysfonctionnement uniquement pour PostGIS :(

> Que se passe-t-il si tu te loggues sur ce serveur et lance ogr2ogr -t_srs EPSG:2154 out.shp "PG:host=postgis-master dbname=extractor_default schemas=recette user=idgo_extractor" lycees_2015

La même chose que dans les logs :
```
ERROR 1: ERREUR:  droit refusé pour la relation lycees_2015
ERROR 1: ERREUR:  droit refusé pour la relation lycees_2015
ERROR 1: ERREUR:  le curseur « ogrpglayerreader0x55af5d138b00 » n'existe pas
```

J'ai corrigé les droits dans la base et ça fonctionne maintenant. Désolé pour cette connerie.

**Comment by bchartier** [comment]
@rouault :
En fait, les 2 cas de figure étaient liés. ogr n'arrivait pas à lire le SRS de la table parce qu'il n'avait pas les droits de lecture sur la table. Maintenant que la question des droits est réglé, OGR arrive à traiter correctement le SRS des données.
C'est dommage que l'erreur `ERROR 1: ERREUR:  droit refusé pour la relation lycees_2015` ne remonte pas dans les logs lorsque ogr essaie d'interpréter le SRS de la table.

Merci pour ton aide et encore désolé pour ces soucis que j'aurais dû comprendre plus rapidement.
